name: "Code Quality"
on: push

jobs: 
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install and Run Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          cd ..
          pylint AWS-MLOps-module --errors-only

      - name: Install and Run Pytest
        run: |
          pip install -U pytest
          pytest --version
          pytest tests/ 

      - name: Install and Run Flake8
        run: | 
          pip install flake8
          flake8 . --count --show-source --statistics

      - name: Terraform Init
        id: init
        working-directory: .
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        working-directory: .
        run: terraform validate -no-color

      - name: Terraform Format
        id: fmt
        working-directory: .
        run: terraform fmt -recursive

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest
          
      - name: Run TFLint
        run: |
          tflint --version
          tflint --init
          tflint -f compact --recursive 

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Get Terratest Dependency
        run: |
          go mod init github.com/konradbcredera/AWS-MLOps-module
          go mod tidy
          go get github.com/gruntwork-io/terratest/modules/terraform

      - name: Terratests
        working-directory: tests/
        run: go test -v ./...

